services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - books-net
    volumes:
      - mysql-volume:/var/lib/mysql

  bookstore:
    image: bookstoreapi:latest
    networks:
      - books-net
    ports:
      - "80:80"
    depends_on:
      - database
    restart: always

networks:
  books-net:

volumes:
  mysql-volume:
